//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;


    public partial class GeodatascanBHP_Entities : DbContext
    {
        public GeodatascanBHP_Entities()
            : base("name=GeodatascanBHP_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TempROT99> TempROT99 { get; set; }
    }
}
