//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expression
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Replacement { get; set; }
        public Nullable<int> ExpressionType { get; set; }
        public Nullable<int> Action { get; set; }
    }
}
